config/routes.rb
Rails.application.routes.draw do
  resources :facturas
  resources :proveedors

  resources :users do
    resources :cotizacion_mns do
      resources :clientes
    end
    resources :cotizacion_dlls do
      resources :clientes
    end
    resources :jobs
  end
    
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/cotizacion_dll.rb
class CotizacionDll < ApplicationRecord
  belongs_to :cliente
  belongs_to :user
  belongs_to :job
  belongs_to :factura
end

app/controllers/cotizacion_dlls_controller.rb
class CotizacionDllsController < ApplicationController
  before_action :set_cotizacion_dll, only: %i[ show edit update destroy ]

  # GET /cotizacion_dlls or /cotizacion_dlls.json
  def index
    @cotizacion_dlls = CotizacionDll.all
  end

  # GET /cotizacion_dlls/1 or /cotizacion_dlls/1.json
  def show
  end

  # GET /cotizacion_dlls/new
  def new
    @cotizacion_dll = CotizacionDll.new
  end

  # GET /cotizacion_dlls/1/edit
  def edit
  end

  # POST /cotizacion_dlls or /cotizacion_dlls.json
  def create
    @cotizacion_dll = CotizacionDll.new(cotizacion_dll_params)

    respond_to do |format|
      if @cotizacion_dll.save
        format.html { redirect_to cotizacion_dll_url(@cotizacion_dll), notice: "Cotizacion dll was successfully created." }
        format.json { render :show, status: :created, location: @cotizacion_dll }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cotizacion_dll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cotizacion_dlls/1 or /cotizacion_dlls/1.json
  def update
    respond_to do |format|
      if @cotizacion_dll.update(cotizacion_dll_params)
        format.html { redirect_to cotizacion_dll_url(@cotizacion_dll), notice: "Cotizacion dll was successfully updated." }
        format.json { render :show, status: :ok, location: @cotizacion_dll }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cotizacion_dll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cotizacion_dlls/1 or /cotizacion_dlls/1.json
  def destroy
    @cotizacion_dll.destroy

    respond_to do |format|
      format.html { redirect_to cotizacion_dlls_url, notice: "Cotizacion dll was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cotizacion_dll
      @cotizacion_dll = CotizacionDll.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cotizacion_dll_params
      params.require(:cotizacion_dll).permit(:cliente_id, :user_id, :job_id, :factura_id, :status)
    end
end

app/helpers/cotizacion_dlls_helper.rb
module CotizacionDllsHelper
end

app/views/cotizacion_dlls/_cotizacion_dll.html.erb
<div id="<%= dom_id cotizacion_dll %>">
  <p>
    <strong>Cliente:</strong>
    <%= cotizacion_dll.cliente_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= cotizacion_dll.user_id %>
  </p>

  <p>
    <strong>Job:</strong>
    <%= cotizacion_dll.job_id %>
  </p>

  <p>
    <strong>Factura:</strong>
    <%= cotizacion_dll.factura_id %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= cotizacion_dll.status %>
  </p>

</div>

app/views/cotizacion_dlls/_form.html.erb
<%= form_with(model: cotizacion_dll) do |form| %>
  <% if cotizacion_dll.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cotizacion_dll.errors.count, "error") %> prohibited this cotizacion_dll from being saved:</h2>

      <ul>
        <% cotizacion_dll.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cliente_id, style: "display: block" %>
    <%= form.text_field :cliente_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :job_id, style: "display: block" %>
    <%= form.text_field :job_id %>
  </div>

  <div>
    <%= form.label :factura_id, style: "display: block" %>
    <%= form.text_field :factura_id %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cotizacion_dlls/edit.html.erb
<h1>Editing cotizacion dll</h1>

<%= render "form", cotizacion_dll: @cotizacion_dll %>

<br>

<div>
  <%= link_to "Show this cotizacion dll", @cotizacion_dll %> |
  <%= link_to "Back to cotizacion dlls", cotizacion_dlls_path %>
</div>

app/views/cotizacion_dlls/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cotizacion dlls</h1>

<div id="cotizacion_dlls">
  <% @cotizacion_dlls.each do |cotizacion_dll| %>
    <%= render cotizacion_dll %>
    <p>
      <%= link_to "Show this cotizacion dll", cotizacion_dll %>
    </p>
  <% end %>
</div>

<%= link_to "New cotizacion dll", new_user_cotizacion_dll_path %>

app/views/cotizacion_dlls/new.html.erb
<h1>New cotizacion dll</h1>

<%= render "form", cotizacion_dll: @cotizacion_dll %>

<br>

<div>
  <%= link_to "Back to cotizacion dlls", cotizacion_dlls_path %>
</div>

app/views/cotizacion_dlls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cotizacion_dll %>

<div>
  <%= link_to "Edit this cotizacion dll", edit_cotizacion_dll_path(@cotizacion_dll) %> |
  <%= link_to "Back to cotizacion dlls", cotizacion_dlls_path %>

  <%= button_to "Destroy this cotizacion dll", @cotizacion_dll, method: :delete %>
</div>