config/routes.rb
Rails.application.routes.draw do
  resources :facturas
  resources :proveedors

  resources :users do
    resources :cotizacion_mns do
      resources :clientes
    end
    resources :cotizacion_dlls do
      resources :clientes
    end
    resources :jobs
  end
    
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/cotizacion_mn.rb
class CotizacionMn < ApplicationRecord
  belongs_to :cliente
  belongs_to :user
  belongs_to :job
  belongs_to :factura
end

app/controllers/cotizacion_mns_controller.rb
class CotizacionMnsController < ApplicationController
  before_action :set_cotizacion_mn, only: %i[ show edit update destroy ]

  # GET /cotizacion_mns or /cotizacion_mns.json
  def index
    @cotizacion_mns = CotizacionMn.all
  end

  # GET /cotizacion_mns/1 or /cotizacion_mns/1.json
  def show
  end

  # GET /cotizacion_mns/new
  def new
    @cotizacion_mn = CotizacionMn.new
  end

  # GET /cotizacion_mns/1/edit
  def edit
  end

  # POST /cotizacion_mns or /cotizacion_mns.json
  def create
    @cotizacion_mn = CotizacionMn.new(cotizacion_mn_params)

    respond_to do |format|
      if @cotizacion_mn.save
        format.html { redirect_to cotizacion_mn_url(@cotizacion_mn), notice: "Cotizacion mn was successfully created." }
        format.json { render :show, status: :created, location: @cotizacion_mn }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cotizacion_mn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cotizacion_mns/1 or /cotizacion_mns/1.json
  def update
    respond_to do |format|
      if @cotizacion_mn.update(cotizacion_mn_params)
        format.html { redirect_to cotizacion_mn_url(@cotizacion_mn), notice: "Cotizacion mn was successfully updated." }
        format.json { render :show, status: :ok, location: @cotizacion_mn }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cotizacion_mn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cotizacion_mns/1 or /cotizacion_mns/1.json
  def destroy
    @cotizacion_mn.destroy

    respond_to do |format|
      format.html { redirect_to cotizacion_mns_url, notice: "Cotizacion mn was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cotizacion_mn
      @cotizacion_mn = CotizacionMn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cotizacion_mn_params
      params.require(:cotizacion_mn).permit(:cliente_id, :user_id, :job_id, :factura_id, :status)
    end
end

app/helpers/cotizacion_mns_helper.rb
module CotizacionMnsHelper
end

app/views/cotizacion_mns/_cotizacion_mn.html.erb
<div id="<%= dom_id cotizacion_mn %>">
  <p>
    <strong>Cliente:</strong>
    <%= cotizacion_mn.cliente_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= cotizacion_mn.user_id %>
  </p>

  <p>
    <strong>Job:</strong>
    <%= cotizacion_mn.job_id %>
  </p>

  <p>
    <strong>Factura:</strong>
    <%= cotizacion_mn.factura_id %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= cotizacion_mn.status %>
  </p>

</div>

app/views/cotizacion_mns/_form.html.erb
<%= form_with(model: user_cotizacion_mn) do |form| %>
  <% if @cotizacion_mn.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_cotizacion_mn.errors.count, "error") %> prohibited this cotizacion_mn from being saved:</h2>

      <ul>
        <% user_cotizacion_mn.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cliente_id, style: "display: block" %>
    <%= form.text_field :cliente_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :job_id, style: "display: block" %>
    <%= form.text_field :job_id %>
  </div>

  <div>
    <%= form.label :factura_id, style: "display: block" %>
    <%= form.text_field :factura_id %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cotizacion_mns/edit.html.erb
<h1>Editing cotizacion mn</h1>

<%= render "form", cotizacion_mn: @cotizacion_mn %>

<br>

<div>
  <%= link_to "Show this cotizacion mn", @cotizacion_mn %> |
  <%= link_to "Back to cotizacion mns", cotizacion_mns_path %>
</div>

app/views/cotizacion_mns/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cotizacion mns</h1>

<div id="cotizacion_mns">
  <% @cotizacion_mns.each do |cotizacion_mn| %>
    <%= render cotizacion_mn %>
    <p>
      <%= link_to "Show this cotizacion mn", user_cotizacion_mn %>
    </p>
  <% end %>
</div>

<%= link_to "New cotizacion mn", new_user_cotizacion_mn_path %>

app/views/cotizacion_mns/new.html.erb
<h1>New cotizacion mn</h1>

<%= render "form", user_cotizacion_mn: @user_cotizacion_mn %>

<br>

<div>
  <%= link_to "Back to cotizacion mns", user_cotizacion_mns_path %>
</div>

app/views/cotizacion_mns/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cotizacion_mn %>

<div>
  <%= link_to "Edit this cotizacion mn", edit_cotizacion_mn_path(@cotizacion_mn) %> |
  <%= link_to "Back to cotizacion mns", cotizacion_mns_path %>

  <%= button_to "Destroy this cotizacion mn", @cotizacion_mn, method: :delete %>
</div>